image_post/image_post/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_post/post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post, name='post'),
]

image_post/post/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import FileExtensionValidator
import uuid

# Create your models here.
def image_path(instance, filename):
    return 'images/{}.{}'.format(str(instance.created_date) + "_" + str(uuid.uuid4()), filename.split('.')[-1])


class Image(models.Model):
    image = models.ImageField(
        validators=[FileExtensionValidator(['png', 'jpg'])], upload_to=image_path)
    title = models.CharField(max_length=30)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.title)

image_post/post/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    title=forms.CharField(max_length=15)
    image=forms.ImageField()

    class Meta:
        model = Image
        fields = ("title", "image")

image_post/post/views.py
from django.db.models.fields.files import ImageField
from django.forms.forms import Form
from django.shortcuts import render, redirect
from .forms import ImageForm
from .models import Image
import uuid

# Create your views here.

def index(request):
  form = ImageForm()
  context = {
    "form" : form,
    "images" : Image.objects.order_by('-created_date').all(),
  }
  return render(request, 'index.html', context)


def post(request):
  form = ImageForm(request.POST, request.FILES)
  if form.is_valid():
    post = form.save()
    return redirect('/')
  return render(request, 'index.html', {'form': form})

image_post/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <form method="POST" action="{% url 'post:post' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{form.as_p}}
    {{ form.media }}
    <input type="submit" value="送信">
  </form>
  {% for i in images %}
    <a href={{i.image.url}}><img src={{i.image.url}} width=80 height=80></a>
  {% endfor %}

</body>
</html>